%% E143_ampScreen_showImgs
% amplifier screen

parentDir='/Users/iandardani/Dropbox (RajLab)/Shared_IanD/clamp2';
cd(parentDir)
exampleImagesDir='paper/exampleImages/E143_amplifierScreen/';
exampleInputsFile='E143_amplifierScreen_ExampleImagesInputs.xlsx';

TexAll=readtable(fullfile(parentDir,filesep,exampleImagesDir,exampleInputsFile));


%% GFP clampFISH 2.0 + conventional RNA FISH. Amplifier set 1
panelID=1;
outFile=fullfile(parentDir,exampleImagesDir,['panel',num2str(panelID),'_GFP']);
S=Table2makeImgPanelsInputs(TexAll(TexAll.panelID==panelID,:));


[fig,scalingMinMax]=makeImgPanels(...
    S.imgFiles,...
    S.outColors,...
    'outFile',outFile,...
    'rotateDegrees',S.rotateDegrees,...
    'zplanes',S.zplanes,...
    'boundingbox',S.boundingbox,...
    'scalingMinMax',S.scalingInput,...
    'layoutMatrix',S.layoutMatrix,...
    'fontSize',20,...
    'figWidth',2048,...
    'exportFigToFile',true,...
    'inPanelLabels',S.inPanelLabels);

%% EGFR clampFISH 2.0 + conventional RNA FISH. Amplifier set 1
panelID=2;
outFile=fullfile(parentDir,exampleImagesDir,['panel',num2str(panelID),'_EGFR']);
S=Table2makeImgPanelsInputs(TexAll(TexAll.panelID==panelID,:));

[fig,scalingMinMax]=makeImgPanels(...
    S.imgFiles,...
    S.outColors,...
    'outFile',outFile,...
    'rotateDegrees',S.rotateDegrees,...
    'zplanes',S.zplanes,...
    'boundingbox',S.boundingbox,...
    'scalingMinMax',S.scalingInput,...
    'layoutMatrix',S.layoutMatrix,...
    'fontSize',20,...
    'figWidth',2048,...
    'exportFigToFile',true,...
    'inPanelLabels',S.inPanelLabels);
