% E157part2VsSmFISH_TxnSiteAnalysis_showImgs.m
parentDir='/Users/iandardani/Dropbox (RajLab)/Shared_IanD/clamp2/';
exampleImagesDir='paper/exampleImages/E157part2_TxnSites/';

exampleInputsFile='E157part2_TxnSites_ExampleImagesInputs.xlsx';
%TexAll=readtable(fullfile(parentDir,filesep,exampleImagesDir,exampleInputsFile));
TexAll=readtable('/Users/iandardani/Documents/E157part2_TxnSites_ExampleImagesInputs.xlsx');
%tiffParentDir='/Volumes/IAND_04/E158_tissue/scan/scan1_TumorFreshFrozen/SubregionArray5x5/';

cd(parentDir)
%% Panel inputs - clampFISH 2.0 

panelID=1;
outFile=fullfile(parentDir,exampleImagesDir,['panel',num2str(panelID)]);
S=Table2makeImgPanelsInputs(TexAll(TexAll.panelID==panelID,:));
%S.scalingInput(2,:)=repmat({{0, 97}},1,size(S.scalingInput,2));

[fig,scalingMinMax]=makeImgPanels(...
    S.imgFiles,...
    S.outColors,...
    'outFile',outFile,...
    'boundingbox',S.boundingbox,...
    'scalingMinMax',S.scalingInput,...
    'layoutMatrix',S.layoutMatrix,...
    'rotateDegrees',S.rotateDegrees,...
    'zplanes',S.zplanes,...
    'fontSize',20,...
    'figWidth',2048,...
    'exportFigToFile',true,...
    'inPanelLabels',S.inPanelLabels);
close all

%% Panel inputs - clampFISH 1.0

panelID=2;
outFile=fullfile(parentDir,exampleImagesDir,['panel',num2str(panelID)]);
S=Table2makeImgPanelsInputs(TexAll(TexAll.panelID==panelID,:));
%S.scalingInput(2,:)=repmat({{0, 97}},1,size(S.scalingInput,2));

[fig,scalingMinMax]=makeImgPanels(...
    S.imgFiles,...
    S.outColors,...
    'outFile',outFile,...
    'boundingbox',S.boundingbox,...
    'scalingMinMax',S.scalingInput,...
    'layoutMatrix',S.layoutMatrix,...
    'rotateDegrees',S.rotateDegrees,...
    'zplanes',S.zplanes,...
    'fontSize',20,...
    'figWidth',2048,...
    'exportFigToFile',true,...
    'inPanelLabels',S.inPanelLabels);
close all