% E158_tissue_showImgs
parentDir='/Users/iandardani/Dropbox (RajLab)/Shared_IanD/clamp2';
exampleImagesDir='paper/exampleImages/E158_tissue/';

exampleInputsFile='E158_tissue_ExampleImagesInputs2.xlsx';
TexAll=readtable(fullfile(parentDir,filesep,exampleImagesDir,exampleInputsFile));

%tiffParentDir='/Volumes/IAND_04/E158_tissue/scan/scan1_TumorFreshFrozen/SubregionArray5x5/';

%% Panel inputs
panelID=1;
outFile=fullfile(parentDir,exampleImagesDir,['panel',num2str(panelID)]);
S=Table2makeImgPanelsInputs(TexAll(TexAll.panelID==panelID,:));
%S.scalingInput(2,:)=repmat({{0, 97}},1,size(S.scalingInput,2));

[fig,scalingMinMax]=makeImgPanels(...
    S.imgFiles,...
    S.outColors,...
    'outFile',outFile,...
    'boundingbox',S.boundingbox,...
    'scalingMinMax',S.scalingInput,...
    'layoutMatrix',S.layoutMatrix,...
    'fontSize',20,...
    'figWidth',2048,...
    'exportFigToFile',true,...
    'inPanelLabels',S.inPanelLabels);

%%
% [floor(1:0.5:(length(scalingMinMax)+.5))',[scalingMinMax{:}]']
%%
panelID=2;
outFile=fullfile(parentDir,exampleImagesDir,['panel',num2str(panelID)]);
S=Table2makeImgPanelsInputs(TexAll(TexAll.panelID==panelID,:));

[fig,scalingMinMax]=makeImgPanels(...
    S.imgFiles,...
    S.outColors,...
    'outFile',outFile,...
    'boundingbox',S.boundingbox,...
    'scalingMinMax',S.scalingInput,...
    'layoutMatrix',S.layoutMatrix,...
    'fontSize',20,...
    'figWidth',2048,...
    'exportFigToFile',true,...
    'inPanelLabels',S.inPanelLabels);

%% 
% panelID=3; % large viewing
% outFile=fullfile(parentDir,exampleImagesDir,['panel',num2str(panelID)]);
% S=Table2makeImgPanelsInputs(TexAll(TexAll.panelID==panelID,:));
% 
% [fig,scalingMinMax]=makeImgPanels(...
%     S.imgFiles,...
%     S.outColors,...
%     'outFile',outFile,...
%     'boundingbox',S.boundingbox,...
%     'scalingMinMax',S.scalingInput,...
%     'layoutMatrix',S.layoutMatrix,...
%     'fontSize',20,...
%     'figWidth',2048,...
%     'exportFigToFile',true,...
%     'inPanelLabels',S.inPanelLabels);
%% Panel inputs - FFPE tissue
panelID=4;
outFile=fullfile(parentDir,exampleImagesDir,['panel',num2str(panelID),'_FFPE']);
S=Table2makeImgPanelsInputs(TexAll(TexAll.panelID==panelID,:));
%S.scalingInput(2,:)=repmat({{0, 97}},1,size(S.scalingInput,2));

[fig,scalingMinMax]=makeImgPanels(...
    S.imgFiles,...
    S.outColors,...
    'outFile',outFile,...
    'boundingbox',S.boundingbox,...
    'scalingMinMax',S.scalingInput,...
    'layoutMatrix',S.layoutMatrix,...
    'fontSize',20,...
    'figWidth',2048,...
    'exportFigToFile',true,...
    'inPanelLabels',S.inPanelLabels);
