% E159part2_scan_showImgs
% high-throughput scan

% call_makeImgPanels
parentDir='/Users/iandardani/Dropbox (RajLab)/Shared_IanD/clamp2/';
exampleImagesDir='paper/exampleImages/E159part2_scan/';

%% Panel inputs
panelID=1;
outFile=fullfile(parentDir,exampleImagesDir,['panel',num2str(panelID),'_ForFigure3']);
exampleInputsFile='E159part2_scan_ExampleImagesInputs2.xlsx';
TexAll=readtable(fullfile(parentDir,filesep,exampleImagesDir,exampleInputsFile));
S=Table2makeImgPanelsInputs(TexAll(TexAll.panelID==panelID,:));
%
[fig,scalingMinMax]=makeImgPanels(...
    S.imgFiles,...
    S.outColors,...
    'outFile',outFile,...
    'boundingbox',S.boundingbox,...
    'scalingMinMax',S.scalingInput,...
    'layoutMatrix',S.layoutMatrix,...
    'segmentationSmoothPixels',10,...
    'fontSize',20,...
    'figWidth',2048,...
    'exportFigToFile',true,...
    'inPanelLabels',S.inPanelLabels,...
    'segmentationImgs',S.segmentationImgs);
%% Panel inputs
panelID=2; % for figure 3 (zoomed in)
outFile=fullfile(parentDir,exampleImagesDir,['panel',num2str(panelID)]);
exampleInputsFile='E159part2_scan_ExampleImagesInputs2.xlsx';
TexAll=readtable(fullfile(parentDir,filesep,exampleImagesDir,exampleInputsFile));
S=Table2makeImgPanelsInputs(TexAll(TexAll.panelID==panelID,:));

[fig,scalingMinMax]=makeImgPanels(...
    S.imgFiles,...
    S.outColors,...
    'outFile',outFile,...
    'boundingbox',S.boundingbox,...
    'scalingMinMax',S.scalingInput,...
    'layoutMatrix',S.layoutMatrix,...
    'segmentationSmoothPixels',10,...
    'fontSize',20,...
    'figWidth',2048,...
    'exportFigToFile',true,...
    'inPanelLabels',S.inPanelLabels,...
    'segmentationImgs',S.segmentationImgs,...
    'segmentationCentermostOnly',true);
%% Panel inputs - 3 is stripping panel
panelID=3;
outFile=fullfile(parentDir,exampleImagesDir,['panel',num2str(panelID),'_stripOfPanel1']);
exampleInputsFile='E159part2_scan_ExampleImagesInputs2.xlsx';
TexAll=readtable(fullfile(parentDir,filesep,exampleImagesDir,exampleInputsFile));
S=Table2makeImgPanelsInputs(TexAll(TexAll.panelID==panelID,:));

[fig,scalingMinMax]=makeImgPanels(...
    S.imgFiles,...
    S.outColors,...
    'outFile',outFile,...
    'boundingbox',S.boundingbox,...
    'scalingMinMax',S.scalingInput,...
    'layoutMatrix',S.layoutMatrix,...
    'segmentationSmoothPixels',10,...
    'fontSize',20,...
    'figWidth',2048,...
    'exportFigToFile',true,...
    'inPanelLabels',S.inPanelLabels,...
    'segmentationCentermostOnly',false);
%    'segmentationImgs',S.segmentationImgs,...
%% Panel inputs - 4 is stripping panel
panelID=4;
outFile=fullfile(parentDir,exampleImagesDir,['panel',num2str(panelID),'_stripOfPanel1']);
exampleInputsFile='E159part2_scan_ExampleImagesInputs2.xlsx';
TexAll=readtable(fullfile(parentDir,filesep,exampleImagesDir,exampleInputsFile));
S=Table2makeImgPanelsInputs(TexAll(TexAll.panelID==panelID,:));

[fig,scalingMinMax]=makeImgPanels(...
    S.imgFiles,...
    S.outColors,...
    'outFile',outFile,...
    'boundingbox',S.boundingbox,...
    'scalingMinMax',S.scalingInput,...
    'layoutMatrix',S.layoutMatrix,...
    'segmentationSmoothPixels',10,...
    'fontSize',20,...
    'figWidth',2048,...
    'exportFigToFile',true,...
    'inPanelLabels',S.inPanelLabels,...
    'segmentationCentermostOnly',false);
%    'segmentationImgs',S.segmentationImgs,...
%% export to eps file
%figure(fig)
%exportgraphics(fig, 'Fig4096wide.pdf', 'ContentType', 'vector','Resolution',300);
%%
% outName=['panel7p5widthFromPrint',num2str(panelID)];
% outFile=fullfile(parentDir,exampleImagesDir,outName);
% figure(fig);
% print(outFile,'-depsc')%,'-tiff')


% [floor(1:0.5:16.5)',[scalingMinMax{:}]']